### PR TITLE
Fix Bug: Decimal not Accepted as Valid Item Unit Price

### LINKED ISSUE #177: [Bug] Items add (unit price)
I realise that there is now a bug when the user tries to add an item with a valid unit price (e.g., 2.5). A screenshot is attached below.
Screenshot (6)

### PR DESCRIPTION
**Pull request by zikunz**

### CODE REVIEW

File: src/main/java/seedu/easylog/commands/itemscommands/ItemsPromptPriceCommand.java [hunk 1]
```diff
@@ -18,9 +17,10 @@
...
             NonNumericItemPriceException {
         ui.promptItemPrice();
+
         String priceInString = ui.askForUserInput();
         try {
-            Integer.parseInt(priceInString);
+            Double.parseDouble(priceInString);
         } catch (NumberFormatException e) {
             throw new NonNumericItemPriceException();
         }
```
Comment (ongweisheng) [inline src/main/java/seedu/easylog/commands/itemscommands/ItemsPromptPriceCommand.java:26]: think this part is irrelevant, but we can leave it for now

Comment (ongweisheng) [reply src/main/java/seedu/easylog/commands/itemscommands/ItemsPromptPriceCommand.java:26]: numberformat exception can be caught below in the processPriceInput

**Review by ongweisheng — APPROVED** [review]

File: src/main/java/seedu/easylog/commands/itemscommands/ItemsPromptPriceCommand.java (hunk 1 above)
Comment (zikunz) [reply src/main/java/seedu/easylog/commands/itemscommands/ItemsPromptPriceCommand.java:26]: I will check all exceptions and make sure they are caught at right place and print correct error message when adding an item later today :)
