### PR TITLE
Fix items add consistency issues and exceptions problems

### LINKED ISSUE #201: Ensure all exceptions are caught in the right place and Ui shows the correct error message

### LINKED ISSUE #209: Change items add to follow the style of orders add
To make a more cohesive product in terms of logic, please change the items add command so that it is consistent with the orders add command. Specifically, the user needs to input item price and item command in 1 line. Also, the user will be prompted again and again if a pair of valid item price and stock is not given.

### PR DESCRIPTION
**Pull request by zikunz**
The items add command of this version of easyLog is consistent with its orders add command. Specifically, the user needs to input item price and item command in 1 line. Also, the user will be prompted again and again if a pair of valid item price and stock is not given. The coding style is also improved.

### CODE REVIEW

**Comment by zikunz** [comment]
> The items add command of this version of easyLog is consistent with its orders add command. Specifically, the user needs to input item price and item command in 1 line. Also, the user will be prompted again and again if a pair of valid item price and stock is not given. The coding style is also improved.



> The items add command of this version of easyLog is consistent with its orders add command. Specifically, the user needs to input item price and item command in 1 line. Also, the user will be prompted again and again if a pair of valid item price and stock is not given. The coding style is also improved.

The Ui class and Message class are not done yet. It is intentionally left for another member to do.

File: src/main/java/seedu/easylog/commands/itemscommands/ItemsAddCommand.java [hunk 1]
```diff
@@ -28,28 +24,26 @@
...
-        if (itemDescription.equals("")) {
-            throw new EmptyNameException();
+            throws EmptyItemNameException, NonIntegerItemStockException, NonNumericItemPriceException,
+            InvalidTotalItemStockException, NullItemNameException, NullItemStockException, EmptyItemStockException,
+            InvalidItemStockException {
+        if (itemDescription == null) {
+            throw new NullItemNameException();
+        }
+
+        String itemDescriptionAfterTrimming = itemDescription.trim();
```
Comment (ongweisheng) [inline src/main/java/seedu/easylog/commands/itemscommands/ItemsAddCommand.java]: no need for item description to be trimmed because inputs are alrd trimmed in the Ui askForUserInput() method.

File: src/main/java/seedu/easylog/parser/ItemsParser.java [hunk 2]
```diff
@@ -209,4 +199,116 @@ public void processUpdateAttributeInput(String updateInput, int itemIndex, ItemM
...
+
+    public BigDecimal itemPriceInStringToBigDecimalFormat(String itemPriceInString) throws NullItemPriceException,
+            EmptyItemPriceException, NonNumericItemPriceException, InvalidItemPriceException {
+        if (itemPriceInString == null) {
+            throw new NullItemPriceException();
+        }
+
+        String itemPriceInStringAfterTrimming = itemPriceInString.trim();
+        if (itemPriceInStringAfterTrimming.equals("")) {
+            throw new EmptyItemPriceException();
```
Comment (ongweisheng) [inline src/main/java/seedu/easylog/parser/ItemsParser.java]: same as first comment, user input is always automatically trimmed before processing the input

File: src/main/java/seedu/easylog/parser/ItemsParser.java [hunk 3]
```diff
@@ -209,4 +199,116 @@ public void processUpdateAttributeInput(String updateInput, int itemIndex, ItemM
...
+
+    public int itemStockInStringToIntegerFormat(String itemStockInString) throws NullItemStockException,
+            EmptyItemStockException, NonIntegerItemStockException, InvalidItemStockException {
+        if (itemStockInString == null) {
+            throw new NullItemStockException();
+        }
+
+        String itemStockInStringAfterTrimming = itemStockInString.trim();
+        if (itemStockInStringAfterTrimming.equals("")) {
+            throw new EmptyItemStockException();
```
Comment (ongweisheng) [inline src/main/java/seedu/easylog/parser/ItemsParser.java]: same as first and 2nd comment

**Review by ongweisheng — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/easylog/commands/itemscommands/ItemsAddCommand.java (hunk 1 above)
Comment (zikunz) [reply src/main/java/seedu/easylog/commands/itemscommands/ItemsAddCommand.java]: I see, will make changes to it :)

File: src/main/java/seedu/easylog/parser/ItemsParser.java (hunk 2 above)
Comment (zikunz) [reply src/main/java/seedu/easylog/parser/ItemsParser.java]: I see, will make changes to it :)

File: src/main/java/seedu/easylog/parser/ItemsParser.java (hunk 3 above)
Comment (zikunz) [reply src/main/java/seedu/easylog/parser/ItemsParser.java]: I see, will make changes to it :)

**Review by ongweisheng — APPROVED** [review]
